# PostgreSQL. Versions 9.1 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: watches_development
  port: 54320
  host: localhost
  username: postgres

test:
  <<: *default
  database: watches_test
  port: 54320
  host: localhost
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['postgres_host'] %>
  password: <%= ENV['postgres_password'] %>
  username: postgres
  database: watches_production

